### PR TITLE
Adding XML as a requirement

### PR DESCRIPTION
**Pull request by jdblischak**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

I noticed that the function `read.ctv` from [ctv](https://cran.r-project.org/package=ctv) did not work when installed via conda.

```
> x <- ctv::read.ctv(system.file('ctv', 'Econometrics.ctv', package = 'ctv'))
Error in loadNamespace(name) : there is no package called ‘XML’
Calls: <Anonymous> ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted
```

Surprisingly this important dependency is only listed as a suggestion for the package. I assume this is because the package XML can be difficult to install on some machines (I remember I've had issues with it in the past). Since conda-forge provides r-xml, installation shouldn't be an issue. Thus I added r-xml as a dependency (and added a test to ensure the package functions properly).

@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by jdblischak** [comment]
@conda-forge-admin, please lint

**Comment by jdblischak** [comment]
The linter passed now that a new conda-smithy has been released (and contains https://github.com/conda-forge/conda-smithy/pull/966).

**Comment by jdblischak** [comment]
@bgruening Could you please review/merge this PR? I'm not a maintainer yet.

The only non-standard thing I did was add an extra requirement (r-xml). It is only listed as a suggested requirement on CRAN, but is needed for some of the critical functions to work (`read.ctv`).

**Comment by bgruening** [comment]
Merci!

**Comment by jdblischak** [comment]
The CI failed due to a strange error:

```
+ setup_conda_rc /home/conda/feedstock_root /home/conda/recipe_root /home/conda/feedstock_root/.ci_support/linux_target_platformlinux-64.yaml
+ conda clean --lock

ArgumentError: At least one removal target must be given. See 'conda clean --help'.

Exited with code 2
```

I assume this is temporary. I restarted the build:

https://circleci.com/gh/conda-forge/r-ctv-feedstock/12

**Comment by dpryan79** [comment]
The most recent `conda` needs to be fixed or pulled before anything will go through.

**Comment by jdblischak** [comment]
> The most recent conda needs to be fixed or pulled before anything will go through.

@dpryan79 Thanks for saving me from trying to fix this! I'll return to it later then.

**Pull request merged**
